services:

  wiremock:
    image: 'wiremock/wiremock:3.13.2'
    environment:
      WIREMOCK_OPTIONS: '--https-port 8443 --verbose'
    ports:
      - "8081:8080"
      - "8443:8443"
    volumes:
      - ./src/test/resources/wiremock:/home/wiremock
