## server configuration
server.shutdown=immediate

## spring configuration
spring.application.name=web-app-dev

## Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=env
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.group.readiness.include=*
management.endpoint.health.group.readiness.show-components=always
management.endpoint.health.group.readiness.show-details=always
management.endpoint.health.group.liveness.include=*
management.endpoint.health.group.liveness.show-components=always
management.endpoint.health.group.liveness.show-details=always

## OpenAPI config
app.openapi.host=127.0.0.1
springdoc.show-actuator=true
## Default Path is: Scheme(http/https)://${app.openapi.host}:${server.port}/${server.servlet.context-path}/${springdoc.api-docs.version}/api-docs
# e.g., http://loclahost:8080/app/3/api-docs
springdoc.api-docs.enabled=true
## Default Path is: Scheme(http/https)://${app.openapi.host}:${server.port}/${server.servlet.context-path}/swagger-ui.html
# e.g., http://loclahost:8080/app/swagger-ui.html
springdoc.swagger-ui.enabled=true

## Logging config
logging.level.io.akikr=DEBUG

## App Filter logger configs
app.filter.logging-enabled=true
app.filter.include-request-body=true
app.filter.include-request-headers=true
app.filter.include-response-headers=true
app.filter.include-response-body=true
app.filter.max-body-length=10000

## App Rest Client configs
app.external-service.client-base-url=http://localhost:8081/api
app.external-service.client-connect-timeout=20000
app.external-service.client-read-timeout=20000
app.external-service.client-logging-enabled=true
app.external-service.client-include-request-headers=true
app.external-service.client-include-request-body=true
app.external-service.client-include-response-headers=true
app.external-service.client-include-response-body=true
app.external-service.client-max-body-length=10000
